apiVersion: apps/v1
kind: Deployment
metadata:
  name: weathers
  labels:
    app: weathers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weathers
  template:
    metadata:
      labels:
        app: weathers
    spec:
      containers:
      - name: weathers
        image: eunjae0505/weathers
        ports:
        - containerPort: 8000
